---
# them in hiera/{github_login}.yaml

:backends:
  - yaml
:yaml:
  :datadir: "%{::boxen_home}/repo/hiera"
:hierarchy:
  - "host/%{macaddress}"
  - "users/%{github_login}"
  - common
:merge_behavior: deeper
